name: 'GitOps Deploy'
description: ''
inputs:
  host:
    description: 'SSH host of your GitOps repository'
    required: true
    default: 'github.com'
  repository:
    description: 'Path of your GitHub repo (ex. MyName/RepoName)'
    required: true
  ref:
    description: 'Branch or Git identifier to commit on'
    required: true
    default: 'HEAD'
  token:
    description: 'Authentication for GitHub HTTP'
    required: false
  path:
    description: 'Path of the file which configures this service'
    required: true
  field:
    description: 'Location within the YAML to insert the new version/tag, in lodash set syntax https://lodash.com/docs/4.17.15#set'
    required: true
    default: 0.spec.values.image.tag
  repository-field:
    description: 'Location within the YAML containing the image repository'
    required: false
    default: 0.spec.values.image.repository
  new-version:
    description: 'The new version of the app which needs to be set'
    required: true
  aws-access-key-id:
    description: 'AWS access key ID for verifying image verification'
    required: false
  aws-secret-access-key:
    description: 'AWS secret access key for image verification'
    required: false
  aws-session-token:
    description: 'AWS session token for image verification'
    required: false
  aws-region:
    description: 'AWS session region for image verification'
    required: false
    default: 'us-west-2'
outputs:
  commit:
    description: 'Hash of the created commit'
runs:
  using: 'node12'
  main: 'index.js'
